---
driver:
  name: "terraform"
  root_module_directory: "test/integration/fixtures"

  parallelism: 1

  variable_files:
    - "test/integration/fixtures/terraform.tfvars"

provisioner:
  name: "terraform"

platforms:
  -
    name: "linux"

verifier:
  name: "terraform"
  groups:
    -
      name: "local"
      controls:
        - "state_file1"
        - "state_file2"
        - "state_file3"
        - "state_file4"

suites:
  - name: "default"